Repository asacristani/fastapi-rocket-boilerplate, pull requests merged in 2023-10, with the labels that each got.

#5 fix: set dockerfile for production install and skip dev packages
  Dockerfile
Labels: improvement

#3 Ensure node dependencies are installed before installing sdk
  Makefile
Labels: enhancement

#6 ci: :construction_worker: optimize github action
  .github/workflows/ci.yml
Labels: improvement

#2 fix: use pre-commit.ci configs for github-action
  .pre-commit-config.yaml
  README.md
  poetry.lock
  pyproject.toml
Labels: improvement

#13 add_azure_as_future_feature
  README.md
Labels: documentation

#30 Fixed link to pulumi
  README.md
Labels: documentation
